# Policy for the staging env.
# They must use the .staging subdomain (to not conflict)
# and use the proper tls cert
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: vcluster-ingress
spec:
  background: false
  rules:
  - name: staging-domain
    match:
      any:
      - resources:
          kinds:
          - Ingress
          namespaces:
          - staging
    validate:
      failureAction: Enforce
      message: "Ingress hostnames in the 'staging' namespace (from the vcluster) must use the staging domain"
      pattern:
        spec:
          rules:
            - host: "*.staging.cocointhe.cloud"
  - name: add-secretname-to-staging-ingress
    match:
      resources:
        kinds:
        - Ingress
        namespaces:
        - staging
    mutate:
      patchStrategicMerge:
        spec:
          tls:
          - (hosts): []
            secretName: wildcard-staging-cocointhe-cloud-tls