apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iplookup
spec:
  interval: 24h
  chart:
    spec:
      chart: appchart
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: iplookup
        image: gitea.cocointhe.cloud/coco/iplookup:0.1.0
        service: 8080
        env:
          - name: IPINFO_TOKEN
            valueFrom:
              secretKeyRef:
                name: iplookup-secret
                key: IPINFO_TOKEN
        volumeMounts:
          - name: iplookup-data
            mountPath: /app/data
        volumes:
          - name: iplookup-data
            persistentVolumeClaim:
              claimName: iplookup-data
        pvc:
          - iplookup-data
