apiVersion: v1
data:
  IPINFO_TOKEN: ENC[AES256_GCM,data:+EQXI9MiKUPBQm0ZC8+EjELE8PU=,iv:1+Cb9MeE/JFgxpB7zZsfrKjGWprMo5T4zsr9k4KydQc=,tag:eR5TDwiZm2SuNjj6dICbEQ==,type:str]
kind: Secret
metadata:
  name: iplookup-secret
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aU9MeEJMZVZZZ1ovb1BM
        Yk5KTWpFZytLWWhhcjNScEV4MXZ2ZVkzMGpjClBZL0E3UVozODR1RlkzekNoOXV5
        NU1qMGQrMnRvbWV6TGR6RjJYcW45ZWsKLS0tIFdGZmVXVUVtdkZ6OW1lVFI0MTU1
        TFFCWG9JbWZxVHhJV0JnZ3pza1pBWlUKTztqlaxZzg8XOdy12iGuY+7iE+njqJ6v
        vb1X1OYwuVch1RWEqSgYeuI5Q5JWz72YEqsni0IXs3EqiFfxjy/+Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T20:19:55Z"
  mac: ENC[AES256_GCM,data:iK4G+06Csf6uwwfaa7XOO0bdWKdP3jppMd5/TOjrkpYKUySCnkMyDBeI3x+OKT2qN/xYqRtALSH9nVaaFLwAenyelO96OwIM1mu3mtgo6vz5kmZsrDpz5anT6FKZQkXpNfu6nddLm3ihbbmstdflkSqVGT2A9XVtWoQkDOCNXEI=,iv:3G/Cunf20gir5bII4KL9VEbUIJBvJq4ZqWKTVp0ZZW8=,tag:C3XsImxNfFsqOfo/EdXlWA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
