apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc
spec:
  plugin:
    oidc:
      sessionEncryptionKey: ENC[AES256_GCM,data:z2k28yakBzrSRAa/7bJfUu4JYkVZw7hBxZFBCE2fPopuocMJ56QztQWXoLVDGPi/u+RahySah9IYRRMCGW64DA==,iv:XrCuBqN7oZNLEbmHATV7KxRUNDi+BMom06PftOVX1FM=,tag:AVOPlcSIBM5h9sq2bolvzA==,type:str]
      providerURL: ENC[AES256_GCM,data:XIOX4p31R22p4KWr+mqd+HKNEvIFHFqAzU2eyIlCZpE=,iv:kfIw+JVKiH0dKQk05iV0UB939xn57F986YSV92UhDuo=,tag:OMg/ral76AQBkiW2C586TQ==,type:str]
      ClientId: ENC[AES256_GCM,data:jr9+XMczsLBQasDJYgWOYQvDRPU/J21eZ2h3PtNiyHyx7zSo,iv:DrbCkKLK+9noGuQsGvwlhlfQcKstFWzoLTns4Dsoxaw=,tag:JotMASdjTz1OGOsDWIQ6RQ==,type:str]
      ClientSecret: ENC[AES256_GCM,data:wtuynKWZgGSkbAxtWr7YKc+Pwa9yakfwQ4vLqWjVgUA=,iv:B6wRYeLCJE0CZaOAq8hRtksGZP9Z1Rmqq5OKM0G/VXI=,tag:Hkjj5Xkn57CkpaNFZT30ng==,type:str]
      callbackURL: ENC[AES256_GCM,data:D6hC/4P6beAH6G8tYzqTVw==,iv:R3PVc6gprHHyi9V5rhHyKbBNsFYHg+8gV4BIDSYmspM=,tag:5pppzIT/Jq4sBlw/DeLBBA==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd2htbjh2QXpoRzFFUDBL
        ZStqZG9BdXd2MVNYSFFKcFNTV1A0SXhOSTBRCmhFcFBuWXIrWkpKb0dBQXBlNWh4
        dXlFaThMeWRrcFhzY2FDSlFZeFMxWEUKLS0tIFpxTEZnQm9icFBRaktBaTFLVk1I
        NU80ZzBhempiam1RKzJlTExEeDM1UU0K5WsV2v2Q9vR72DYmNB6ZrVdzOvoYv/8c
        ktzrP6I36THs+nx1TnWwu4yGGisyaiak1Y2exeoKFl7zyrbu567MMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-10T12:34:01Z"
  mac: ENC[AES256_GCM,data:LOmTdDZ2dBPC5cKa4c3WlpBTg3PNsp5qS8Hnp9mnuJLK6HnHj51VFGkxtHBfUJNCorky64gAqnqQ0g+np24cbsDwMXnmNADtjZmYR9OjGC2UvrdWz59RR62ygT3JfEVHnNa+DFa9Vj0m35zGa7h2XmOJjhJpR+7mPQzPnLTCb68=,iv:+B0tii/nWU+rYxiq+iEbsdCMECuxT/VXY5x1yATj11Q=,tag:B0CvZijY6fxaotBNrf5hIw==,type:str]
  encrypted_regex: ^oidc$
  version: 3.11.0
