apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 24h
  url: https://aureq.github.io/cert-manager-webhook-ovh
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager-webhook-ovh
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-ovh
      interval: 1h
  releaseName: cert-manager-webhook-ovh
  valuesFrom:
    - kind: Secret
      name: ovh-webhook-config
