apiVersion: v1
stringData:
  token: ENC[AES256_GCM,data:homnzS4l7S/YlxdScrUNLy7GRuPej7HOrr51DjZjnpiZI9fWRJezWuEvgey5BRbnS1C7jseDEGHU1SPWF+Kz4GyUHfvQBOFntG0wgjW2t6MAjrX/fDFPi54tsc8J,iv:9X64UeKWE7u+mTK40VtyZKrilcsauprpj85MmmNufFc=,tag:/qbLXsnNu/3Hq3hlXGMt3g==,type:str]
kind: Secret
metadata:
  name: github-commit-update-token
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbXFNTXRTQlQ2MkdidnNY
        Nm5ZbWN3eVlUN1BMS2ttQTk0RHo0Lyt4bWxnClNkdzZNUDlPOGRnejltMXhWQjlC
        NnBSWHZic2JxWGdyak5mTzl0K3VXRjgKLS0tIDEvd1Bod0MyOHozZUZmY2JwTFZD
        a3puQlpNaDdEeXZGL3BPVi9ac0xhckkKwnQUuNd7X0qMZqGozSFBA26mF4vUcwOg
        ZN0y/+M8FaQAaydWbrpgrdt9PYaCqrMcVNb8WRTGWdQJ67LxNZN7UA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T22:02:57Z"
  mac: ENC[AES256_GCM,data:wsNsmPNfdLtTi3/9jSS6yMkMe43Ahlc1EdRMFLfSJDCHcw19moJWRIfSvvvzj883FW8WR61ax9k8wYlBSekVW3xtKQiDW4//Z3KDt1yi4HQl5AA8Trvr7azKYLHaRDV9aQ+P6rTnBh8WWtPcKlTTqXN2F5Jo6dWoEkNVlH4zuqA=,iv:BMD6MhkxnmbOpMJ8z3vsx8N4IMgur+S+P447SGShIb0=,tag:CW6zpW5Sv7Wtrtq2kJBvbw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
