apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vcluster
  namespace: staging
spec:
  interval: 24h
  url: https://charts.loft.sh
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vcluster
  namespace: staging
spec:
  interval: 10m
  timeout: 20m
  chart:
    spec:
      chart: vcluster
      version: "0.30.2"
      sourceRef:
        kind: HelmRepository
        name: vcluster
        namespace: staging
  values:
    controlPlane:
      coredns:
        enabled: true
      statefulSet:
        persistence:
          dataVolume: 
          - name: data
            emptyDir: {}
          volumeClaim:
            enabled: false
        scheduling:
          nodeSelector:
            kubernetes.io/hostname: drupelet-3 # set on a worker to avoid overloading the master with 2 cp
    integrations:
      metricsServer:
        enabled: true
        nodes: true
        pods: true
    telemetry:
      enabled: false

    sync:
      fromHost:
        ingressClasses:
          enabled: true
        storageClasses:
          enabled: true
      toHost:
        ingresses:
          enabled: true
