
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: explo
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.5.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: explo
        image: ghcr.io/lumepart/explo:v0.11.5
        env:
        - name: WEEKLY_EXPLORATION_SCHEDULE
          value: "0 4 * * 1"
        - name: EXECUTE_ON_START
          value: "true"
        volumeMounts:
          - name: jellyfin-music
            mountPath: /data
          - name: explo-config
            mountPath: /opt/explo/.env
            subPath: .env
        volumes:
          - name: jellyfin-music
            persistentVolumeClaim:
              claimName: jellyfin-music
          - name: explo-config
            secret:
              secretName: explo-config
