apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-config
stringData:
  values.yaml: ENC[AES256_GCM,data:bShEXlaOt+4G8RRurFZaZ6OjD9MzAW0xOhz9rDhtoxpCNx752PHtJYbLzpQgc/Gsi1ZoNJ5NJLvbh6BDUj8S545Si9HvALW7gZtW6HTDeKB/S7+5sMnwZfBRXYFoQaPxqp8hmOox0QuVtFB9+D+iviaQr8H+kNvjOdaL0CkudckgkV2USgxI9TMYYHDPHC1gP2hON8tMFaqiO4myUnNS72BZpgrDTOttxbzBAFCatd2xH3gKTcS2h15UL0jKto1hmQX9SxYs3gunAOY4RLdHXUUr9XTxaJUtr3UdOOPm1BW7joZJIzMV2kdEjTUuT75T3Ddw2aGOdaRK2RiqDgdVnRi6NR35v8tiC2S1Ktm2OL74LP8U/OZHP7EEWCcbX84H2eICUJy7D63/RTCwoDy0Xqcd9wadvXrRvaTVdItXpNu0DQsfrVOep1VmoCQ=,iv:cUxi52eIP0w+X65wIq73e2N+ldDc8ntqVKQfL5HqQ5k=,tag:slWK+sgo4yAH9+JyEynzzw==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TVJVWk5nRVVIMUJoN2k4
        OWFLSm0zZzJzaVZWejY5V0dxcFEzeW5VWmdnCkRJSGtJQzJROW5KNmNaaDlWdWE4
        RXZMS1NSUllZY2RWekVGNVNDbDlCcTAKLS0tIDN4N2syNFFWTEEwV0VwaDB5Y0xC
        amFxcW12RzBXZ3dwenBoaXUvYUNwWW8KZzmEYiNkkU2E/mvEN42D7VSHZ1Yn2Ps5
        28XmDAyt6i0Sat2/6FAeQupOU4lNOYUOVKMeY18Q7vuctbN83x/Iwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T14:43:18Z"
  mac: ENC[AES256_GCM,data:UzTsHOiR5sd+3adVM1hR0Y87z3b3Ijt2r80OR5cYIoCQkbLyAw+os+iHoNysUzZyBaWQuKpCdLQKUnelemG3Ieq8+KFG64jVkZzY07vNzpyKr+P4xkYOUwHtdn2h9pOBk3y73PkglgBkoXL2bja4mbuLeui0ChwkCB6sg3rg1vk=,iv:6vJeNgQrifTM+fhzgkotMNOc/bSwFUgEygP6xIxySBQ=,tag:k7ExnY7ZkNYdvvY7l8zppg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
