apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falco
spec:
  interval: 24h
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: falco
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: falco
      interval: 1h
  releaseName: falco
  valuesFrom:
  - kind: Secret
    name: falcosidekick-config
  values:
    customRules:
      disable-false-positives.yaml: |
        - rule: Packet socket created in container
          enabled: false
      allow-kube-vip-apiserver.yaml: |
        - rule: Contact K8S API Server From Container
          override: 
            condition: append
          condition: >
            and not k8s.ns.name in (
              kube-vip,
              kyverno,
              vpa,
              nfs-system,
              flux-system,
              system-upgrade,
              cert-manager
            ) and not (
              container.name = "prometheus-server" and
              k8s.ns.name = "watchtower"
            ) and not (
              container.name = "traefik-tunnel" and
              k8s.ns.name = "ingress"
            ) and not (
              container.name = "traefik" and
              k8s.ns.name = "ingress"
            )

      allow-explo-crond.yaml: |
        - rule: Drop and execute new binary in container
          override: 
            condition: append
          condition: >
            and not (
              k8s.ns.name = "media" and
              container.image.repository = "ghcr.io/lumepart/explo" and
              proc.pname = "crond"
            )

    falcosidekick:
      enabled: true
      replicaCount: 1