apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-config
stringData:
  values.yaml: ENC[AES256_GCM,data:LWh/fl3DFCBhlx+Gf1P8ElxWBLerk0nsm595br4IojaA9ZiwAT+lTuwAFIOZ07Kd4ZxIS3cx890nraek/AXquNaMYMKyb709VJr8H3M/3mCqn3DTDwYtOGevtyHvK09ypnVCPeqDKeZ9K5+1Q0+tLCpeSUdUYWKE8DwPx3804DO1Hu1thdubg4bdSf5M0GWKjODI+bbWYQVqyw8rYKiL65SCP8gnRY6qdw6gZp9NJVQP/Do=,iv:L/hfqC0kp6/fFDO7IAbmKd0fv3tXvKXIYRP13klmrwQ=,tag:jh8+6qGZNfaiXxBvgmTzwA==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TVJVWk5nRVVIMUJoN2k4
        OWFLSm0zZzJzaVZWejY5V0dxcFEzeW5VWmdnCkRJSGtJQzJROW5KNmNaaDlWdWE4
        RXZMS1NSUllZY2RWekVGNVNDbDlCcTAKLS0tIDN4N2syNFFWTEEwV0VwaDB5Y0xC
        amFxcW12RzBXZ3dwenBoaXUvYUNwWW8KZzmEYiNkkU2E/mvEN42D7VSHZ1Yn2Ps5
        28XmDAyt6i0Sat2/6FAeQupOU4lNOYUOVKMeY18Q7vuctbN83x/Iwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T19:56:46Z"
  mac: ENC[AES256_GCM,data:91YSUMGO+lS+gmc88eewpOtE9M3m41e+QqiWMHtmeAzhzIRaIZUK9p1BUNJZnOi9uqAjVvfo+HJiaHZpAdvpEDyzh0G+pmnEonlX7+8J9ReVCH3dD+VtU0OCH+y99Q/CK9uhNMvti4VOLG1jm7mqwJ6h/jwf5m5Ti7ljRLqxI7E=,iv:+MDpMJZ14p3b9VGdhE1aqvHVlNAaRmTJ8mLV+IxLSqw=,tag:/oj73DRBiyq8eTVq8RvMNA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
