apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-config
stringData:
  values.yaml:
    falcosidekick:
      config:
        discord:
          webhookurl: ENC[AES256_GCM,data:ahK9vs0yVep3MOaWMEvaHS4kxwH57EZB8NuW1Yxcd8DwA0jGJILtPB8JJlhO2cJlr5T3C4Kjxbk2Vg6bm+XQb0uBCylXpDC2NKGrGDCb/jZnPg0r/6MHKUAGWd+xwJTzoKAL+kR9xD4GMMo6v5cNfYXHfp/1n7BqHQ==,iv:t6uriURPUZL21Vwdo/vpdXL/j28oz5WVvrOQM0eqXrQ=,tag:1timAxGSb8/TotxSbPcLww==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGS3Y5aFgvMCtxNWdMTU5U
        RVRrYVluMXZralNMQWFQUWRPQ2tpQ1A2Z0RnCldXaS9qSlc4elBremdPVnB0d3NM
        TnZKUUNEcGs2UlhmUWxEVlNnbys5VmsKLS0tIFQvRWQ4ZStuTzJZQytDZjlXbFpK
        UzdIcTFsQjhHZStDTTVrdjBhbWZCVHMKR6LsA33qQ1H65BS8VLOFeTYjgMS0aB4r
        aiF6xU0JUlIWW3xlviNMANANa5gDBPPZP5C0gudi6+71qWUMnH183Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T19:48:15Z"
  mac: ENC[AES256_GCM,data:EFEBYD1Duem5Echc2OvRjeOu29hZGX/wondowEJS5QBpdCOkjdvxgv/geX9v06JZqkvzcolW4GCAWiBRMgdATLx3KSAkC6jWlMrEqEA4tsoEQZe48Fvk4HuFTiQnDmq8/AescyFXI76MHdq2CA2UwhcyYneS2Fz4JlxiT/MxvPc=,iv:x3sV1T0QkJvOVe3RhBVyysj797HUqr8K4whILd5KRSY=,tag:ImoJmmFbWmZAWF4jL6yzAQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
