apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grist
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: grist
        image: gristlabs/grist:1.7.8@sha256:5fb6d99b820c60cad9a334a63516ef7e7868aa089815190b95697b8b65db7ae7
        containerSpec:
          envFrom:
            - secretRef:
                name: grist-config
        volumeMounts:
          - name: grist-data
            mountPath: /persist
        volumes:
          - name: grist-data
            persistentVolumeClaim:
              claimName: grist-data
        service: 8484
        pvc:
          - grist-data
        ingress:
          domain: grist.cocointhe.cloud
          public: true
---
# allow accessing the cluster VIP (mainly for the OIDC provider callbacks)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grist-oidc
spec:
  podSelector:
    matchLabels:
      app: grist
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.1.10/32
    ports:
    - protocol: TCP
      port: 443