apiVersion: v1
kind: Secret
metadata:
  name: grist-config
stringData:
  GRIST_OIDC_SP_HOST: ENC[AES256_GCM,data:WzNibWdYw1gTUVomEAm+pBu0lIuPg5c/wIL3r00=,iv:xU6FLlG3IEp0tLajfn6aimzw1PoF/JHvb0F2T5u6DbM=,tag:MUOZ5iMLZzjprv0gepCIWQ==,type:str]
  GRIST_OIDC_IDP_ISSUER: ENC[AES256_GCM,data:UaNxC05rS+aaJZ1ooLIgfrTlQV/+ckRfsPhsxv8/9vrtAPNHHoG5/HcE+HwlskSrbgxauieSG5ab/uj6nHs7JwU=,iv:qdBnz9U2VlIcsLAJQHGtYtBXQOdESgV+yZB1vCiSXPY=,tag:W58FQN9cW4Gup4fMa0lxzQ==,type:str]
  GRIST_OIDC_IDP_SCOPES: ENC[AES256_GCM,data:QtoQIE0Hl9oSigVRh2KE1Lh/imw=,iv:dmU2uTjcgwrLEVgBAujVqPcWlLGc6ERpqPa2NAfNgRo=,tag:W3wY2YYDttUKyM2zqYAw7Q==,type:str]
  GRIST_OIDC_IDP_CLIENT_ID: ENC[AES256_GCM,data:UrHvemwYVq7Ex3LIe5ZXnjW98xGxHY2TmI3EX8aZN8KN0m7s,iv:nbUTEiABj5gOwqbRpj59kwBk1BsQ+XcOaLys/MhoTys=,tag:HhPooUh2Kdlzo9Ckt6F0MQ==,type:str]
  GRIST_OIDC_IDP_CLIENT_SECRET: ENC[AES256_GCM,data:+ADoy4pFguSDDBVlOZ3u3BVbZdHfqIQMWIom2eHtx+Y=,iv:fHupEXGXszIlIF3mZGE7FiyQ+M8N0LMMoxLfzz+1jFg=,tag:7QRlVQUPHPc+bXIOsQFpnA==,type:str]
  GRIST_SESSION_SECRET: ENC[AES256_GCM,data:uekLjVyCAOubui8Rc61XmeEgO2zR+FEaHvcPC9eAhSJIfr5PrqlhQXtOLs2HnJTJ8S4WZzjf/61b11tj42LwHA==,iv:gtegh4YLRRYNAe7aF1LltZfNwNRGowT02cn8Kbsw6YU=,tag:rou6r8BLWXSd6IPHC7VkMg==,type:str]
  GRIST_FORCE_LOGIN: ENC[AES256_GCM,data:JcZ7pQ==,iv:4xmhqFMYp5YZ4R9XVcVdG502VY4Gkvvz4bdgm8t6eFM=,tag:6oChylpB2BSEI5vfv2bKcQ==,type:str]
  GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED: ENC[AES256_GCM,data:mzp87g==,iv:GOJPWEiDEfp3lfssOa4i2ZBSPPvILKJl9NTFo7q/yJ0=,tag:bOqIg+EeEgQbr2IlVSpoXw==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZXM0Ym1BOHFVTUR4RjFi
        c2tGcTJZdy9xOXB2emxjK0JQeFFsZWNDQ0FJCmR1Q0Qwd2NHcmRPdVRFOFZoN3pm
        ZnRDREJaTGNWL2JQK3ppNnBIWmRtTGcKLS0tIGY2aDc1a1hiZGduTXloNFZka08r
        R1hUR3FsZ2RkdTgrVHZMNmFuWmp1M2cKOjXIgJrS1s5VGdLUQ8AFxuhaqByRB/Zu
        zT5i00e9Px3nQ8SuxIk6OaYxwZQPJUhaEgnG6gHsTCaBCYP35YsDvQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T20:54:39Z"
  mac: ENC[AES256_GCM,data:kMB1g7kaKrA23ay+id5BPDrdnFSUl5I3hZqeND6WPLHn3Z1lW/6wDZQukGS3b+HAezTTnxWkALtlPCQ7OUbtya9ChsB28GTJWnzhDBUy2WBiJIdyt3I5yZRB4bGtbg7WBM5wL8Pjw8QIwVXbZg9qa3qPyjRallUiLFcs2LjNGvo=,iv:+oNEp135QnlzDrNNG5SVznLzChYstBbtAE9oIvJtH4E=,tag:hQKJQ5exlBs1jaM2xuVaPA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
