apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: groceries
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.6.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: groceries
        image: gitea.cocointhe.cloud/coco/groceries:0.1.1@sha256:19e1abc4c947a769da6e3f6a9cea5da86bac9db1a1351db2e5b266ee8f3962e6
        containerSpec:
          envFrom:
            - secretRef:
                name: groceries-config
        volumeMounts:
          - name: groceries-data
            mountPath: /app/data
        volumes:
          - name: groceries-data
            persistentVolumeClaim:
              claimName: groceries-data
        service: 8000
        ingress:
          domain: lalistedecourses.cocointhe.cloud
          public: true
        pvc:
          - groceries-data
