apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.7.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: uptime-kuma
        image: louislam/uptime-kuma:2.0.2-slim@sha256:60f3b7d1b55c3d5a9d941f7f91c3e7ac624dea53beb34538fe5546e3664a1e82
        service: 3001
        volumeMounts:
          - name: uptime-kuma-data
            mountPath: /app/data
        volumes:
          - name: uptime-kuma-data
            persistentVolumeClaim:
              claimName: uptime-kuma-data
        ingress:
          domain: uptime.cocointhe.cloud
          public: true
        pvc:
          - uptime-kuma-data
---
# kuma checks
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kuma-checks
spec:
  podSelector:
    matchLabels:
      app: uptime-kuma
  policyTypes:
  - Egress
  egress:
  # for dns/http checks
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
  # for local infra checks
  - to:
    - ipBlock:
        cidr: 192.168.1.0/24

    # for remote infra checks
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tailscale