apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fairwinds
spec:
  interval: 24h
  url: https://charts.fairwinds.com/stable
---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 10m
  timeout: 20m
  chart:
    spec:
      chart: goldilocks
      version: "10.2.0"
      sourceRef:
        kind: HelmRepository
        name: fairwinds
  values:
    controller:
      enabled: true
      flags:
        include-namespaces: "cloud"
    dashboard:
      enabled: false

