apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: autoscaler
spec:
  interval: 24h
  url: https://kubernetes.github.io/autoscaler
---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks-vpa
spec:
  interval: 10m
  timeout: 20m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: vertical-pod-autoscaler
      version: "0.8.0"
      sourceRef:
        kind: HelmRepository
        name: autoscaler
  values:
    updater:
      enabled: true
      extraArgs:
        feature-gates: InPlaceOrRecreate=true
    admissionController:
      enabled: true
      extraArgs:
        feature-gates: InPlaceOrRecreate=true