apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:A0iZQmRqyM+ihTlDvyhjBpylCjmg12Cn3GGavBqjO/Q/ZQ==,iv:OBOk/XQedBej9V4wGYgRNci6yG3QHyTz5eYaPQlQdJY=,tag:pHqCobDN5K6VwbXw51bYxg==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:vMfjsEqF,iv:U/8/OQBy1aR8heRtk0ABC3C9yvWPPOsCneGqueUqPTY=,tag:o8Jk31V3yPyXnkLueT1Ajw==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:Myws08hyoC0Cq9GP4e/qNVvsLyb7sPoGFTgB8ENlu+7vS+0ZHkRNV9256cHe1zfWUUSrfsxLvzCCx6fTpoRNn5PKxyt86QZ4iH3J0I46JYYN+a6uIn4x0ihwmmmf,iv:M9H90oMjaDyHimFJ6ZCLCm5lArOpJmK/qXsCceOxKkw=,tag:URXYSlWe9Wjv0jjtrcOOdw==,type:str]
  RENOVATE_BASE_DIR: ENC[AES256_GCM,data:3HPu1wEr2hOviFxkRQ==,iv:MNquf5VLjJz7TYJWq6R9KtnVUJibvMrLJo5OBd2aevU=,tag:LhiFe60MEdMf+THUjnKTWA==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU2IrZkZsZDRvTm8relpY
        ejVTeHNRZk5ZODk5cHN1M2hZMmVCZkhiSkJrCi8wNmVQeWk3NzFyUXlubTNZVkEr
        cUtkSTNBMHd4SVdKNTl5SldMdStjRncKLS0tIFVYeTc1UHRNVnAwWVlCMXdJUU1B
        Q2M1SVExcERUeG9BM0pGbXRhN0ViaUkKp19uWMKqVGzu1xfXobLoqXtXwWtLifIJ
        PDncIz+GaAb4X3QU3AwlA8jfnhhOJhXQqQGoDKcT5SIo+AhGEARVhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T21:23:54Z"
  mac: ENC[AES256_GCM,data:uyh0h1anZqariGfYixOc2VOzstxIey+Vt2SArjYrY07O/xPyh4Su3pIEvOfpP2v6zKWBmwHDXQ2SDshEP/IaOZ293M4kMXNEqR/VnHGQBDi/ZvC+6c4XOL8BGPOwsqNdeWtEbqUOIeYvmWlEyMNhjTXKyt5FGLsrc6xQfzpzvRo=,iv:lt1cqhfcUagLAvhid1or0QitwbvB4rB4FWsLY5Q0KDY=,tag:HsiXib+V3o0oDuOa98taJQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
