apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-csi
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-csi
spec:
  interval: 10m
  timeout: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.13.1"
      sourceRef:
        kind: HelmRepository
        name: nfs-csi
      interval: 1h
  releaseName: nfs-csi
  values:
    externalSnapshotter:
      enabled: false
      customResourceDefinitions:
        enabled: false
    volumeSnapshotClass:
      create: false
      name: nfs-csi-snapshots
    storageClass:
      create: true
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      name: nfs-csi
      parameters:
        server: nfs-server.nfs-system
        share: /
        subDir: "${pvc.metadata.namespace}-${pvc.metadata.name}"
        onDelete: retain
        mountPermissions: "0777"
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      mountOptions:
        - nfsvers=4.2