apiVersion: v1
kind: Secret
metadata:
  name: prom-config
stringData:
  values.yaml: ENC[AES256_GCM,data:mI7mYZCkBnbAgA6cO8c/Xb61Bfg9rrx7B60avT3VAAcH832+PBvAWzKasMKkq8ZTEy/crHzrAQi4m6hOx8WSIKq9Nt2ePwY4JnAL3QXJdjydPaYCqRlbbjvgZUqtiZ+o7eiKSmQ/2I3JVQ4XBuLTI499FflKhDD7wN/IjtpUAcZJrv4+enK4FCJueuNyJiZqT+wEJHLu36sjpBwJAawl3+Eh9oRUZUAwGHPZo9oEJNAv1LjMKM1C2CH30wvn9a3buDMCOfHIPZcyhAgTWV58dXYIKfKKqnHqvWrUDwUb5C4YZZksKzvs5JOX5MfaftJeZSk+6Z7R1oF4nfu7Vwu5WAk1/HKDo3xn+UNVloXz7McDL3jIVHqUROGEOp1Svl4VnakXupsAdW+5DRPmXljtszQwTzeRZT87LNi9vlsidyAk5bfdDW4RWC81XY9YztzsKwes8wNeUFacZ+I9t1fW0Fbdxhl8dVP6kkxG3AIM3xpzihTHALUS848x0MPCa7JC+IA5Vozr8njEE+wFA8JxzBBvntCi4ucEQ0OcyBDN70m6vN/GLd0Syig14ypBy4la4gMOb5TKOhd4nmXpjU2hlJkJqZ9YlUKrf7iajH2+gGufItDg9kGCUBA0WQAtio8iYo0t+qoNtEeFRueP8GPYtH1Indp6ROvR1DBqEalYC9m2iUKyW5CIp4LoNkuquIGXYiY3r0aIgOVy8QMsQ7ljQMO6zMiZdvMVXKd/n7nIiw87uygL9IcrxT4/Z6vCtK08oluxLfYYDrKoFqgYK38ibCgfxkgAwUcdsPeHgoM=,iv:o1DkmPQ5MOpSKUZVzzxSk8O1u+awBH9CViA6qaiXATg=,tag:C/4FKHieDiiamhlwZfk9jw==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNnBPNTZleTZGLzdOd29F
        VWdUeFBPRFdpYzFWSjBGU3pMV3VpQ2FKUG5JCklrbmxEYnFSdVNBZ3hFS2dGNUxC
        T1AzemxGSU5jMTl1bWx1bkpvZ0VRZEUKLS0tIER3UjlqTnlWNWc1K012aldUVEVI
        UE1KT1BEc0c5L2tNQVBlRVBsVlBDTjQKh33j1yOzEmpI24EKDHgJOoFIyKXgLC6u
        eIBxuRjfNLexjQ90M/QoRSwIKr1lQ2ZB01/oiYdgta5WR1IB4FkU+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T16:44:11Z"
  mac: ENC[AES256_GCM,data:rDi7lyH69SHd6EqWsGcPCvDxfC/p0ZorpoO9VOkquZk9KqXa/T0R9bc+PZXus+Y09hZJ2hquwXlMOt4GlRhHVLchOXj9RzrWM4q5K+rxb27g7Rz5mAInmvCOUt7WCsrL1HSYcqHZXrGZrvPkk1FugueBtd6lfMW6pYXH5Z5ZdoM=,iv:mbyMtpiDeQFND2Bu3yuS3HC2Oqn1GcokMBu8Zj++bkg=,tag:wqFo77RALxFt2+lRRjmQZw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
